
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.osmosewebservice.StartRecordingParameters;
import org.datacontract.schemas._2004._07.osmosewebservice.StopRecordingParameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IOsmoseWebService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.osmosewebservice.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IOsmoseWebService {


    /**
     * 
     * @param startRecordingParameters
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "StartRecording", action = "http://tempuri.org/IOsmoseWebService/StartRecording")
    @WebResult(name = "StartRecordingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StartRecording", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartRecording")
    @ResponseWrapper(localName = "StartRecordingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StartRecordingResponse")
    public Boolean startRecording(
        @WebParam(name = "startRecordingParameters", targetNamespace = "http://tempuri.org/")
        StartRecordingParameters startRecordingParameters);

    /**
     * 
     * @param stopRecordingParameters
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "StopRecording", action = "http://tempuri.org/IOsmoseWebService/StopRecording")
    @WebResult(name = "StopRecordingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "StopRecording", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopRecording")
    @ResponseWrapper(localName = "StopRecordingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.StopRecordingResponse")
    public Boolean stopRecording(
        @WebParam(name = "stopRecordingParameters", targetNamespace = "http://tempuri.org/")
        StopRecordingParameters stopRecordingParameters);

}
